### ISSUE TITLE
Branch2

### ISSUE THREAD

**Issue by jaschultz** [stridespace/manual#2]
<pre>
testspace:
</pre>

**Comment by ivailop** [comment]
**Build 1** session

Specs: 2 <sub><sup>:heavy_check_mark::heavy_check_mark:</sup></sub>
Scenarios: [2, 0] (3)
Runtime: 57 s (on 2019-01-11)
<sub>Managed by [Testspace](https://open.stridespace.com/spaces/9175/cycles/127)</sub>
